---
- name: Building and deploying docker image
  hosts: myhost
  vars:
    image_name: music-genre-clustering
    image_tag: latest
    tar_path: /tmp/music-genre-app.tar

  tasks:
    - name: Downloading python requirements
      ansible.builtin.command:
          cmd: apk add py3-requests py3-packaging
      become: true
      changed_when: false
    - name: Build an image
      delegate_to: localhost
      ansible.builtin.command:
        cmd: docker build -t {{ image_name }}:{{ image_tag }} ../
    - name: Archive image to tar
      delegate_to: localhost
      ansible.builtin.command:
        cmd: docker save -o {{ tar_path }} {{ image_name }}:{{ image_tag }}
    - name: Copy tar file to host
      ansible.builtin.copy:
        src: "{{ tar_path }}"
        dest: "{{ tar_path }}"
    - name: Load image from tar
      become: true
      ansible.builtin.command:
        cmd: docker load -i {{ tar_path }}
    - name: Start container
      become: true
      ansible.builtin.command:
        cmd: docker run -d --name music-genre-app-container -p 8080:8080 {{ image_name }}:{{ image_tag }}